config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :blogs

    root to: "users#index"
  end

  get 'home', to: 'home#home'
  
  get 'about', to: 'home#about'

  get 'charges', to: 'charges#new'

  devise_for :users
  resources :blogs
  resources :charges
  
  root to: "blogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      if !current_user.roles.include?(:admin)
        redirect_to root_path, notice: "You are not allowed here"
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/blogs_controller.rb
module Admin
  class BlogsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Blog.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Blog.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  	if logged_in?(:admin, :current_user)
  		@page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page"
    end
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  def destroy
  	if logged_in?(:admin, :current_user)
			@blog.destroy
    	redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
    else
    	redirect_to blogs_path, notice: "You are not authorized to access this page"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blog_params
      params.require(:blog).permit(:title, :body, :date)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(path)
		"active" if current_page?(path)
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title, class: "form-control input-lg", placeholder: "Title" %>
  </div>

  <br />

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body, class: "form-control input-lg", placeholder: "Body" %>
  </div>

  <br />

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :blog_date, class: "form-control input-lg", placeholder: "Date" %>
  </div>

  <br />

  <div class="actions">
    <%= form.submit class: "btn btn-block btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
			<h1>Edit Blog</h1>

			<%= render 'form', blog: @blog %>

			<br />

			<%= link_to 'Show', @blog, class: "btn btn-block btn-info" %>

			<br />

			<%= link_to 'Back', blogs_path, class: "btn btn-block btn-warning" %>
		</div>
		<div class="col-md-4"></div>
	</div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <%= render 'shared/nav' %>
  <p id="notice"><%= notice %></p>

  <h1>Blogs</h1>

  <div class="new-bl">
    <%= link_to 'New Blog', new_blog_path, class: "btn btn-default" %>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @blogs.each do |blog| %>
        <tr>
          <td><%= blog.title %></td>
          <td><%= blog.body %></td>
          <td><%= blog.date %></td>
          <td><%= link_to '', blog, id: "show_#{blog.id}", class: "glyphicon glyphicon-menu-hamburger index-icons" %></td>
          <td><%= link_to '', edit_blog_path(blog), id: "edit_#{blog.id}", class: 'glyphicon glyphicon-edit index-icons' %></td>
          <td><%= link_to '', blog, method: :delete, id: "delete_blog_#{blog.id}_from_index", class: 'glyphicon glyphicon-trash index-icons', data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
			<h1>New Blog</h1>

			<%= render 'form', blog: @blog %>

			<br />

			<%= link_to 'Back', blogs_path, class: "btn btn-block btn-info" %>
		</div>
		<div class="col-md-4"></div>
	</div>
</div>

app/views/blogs/show.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">
	<div class="jumbotron sh-jum">
		<div class="container-fluid">
			<p id="notice"><%= notice %></p>

			<p><h1><%= @blog.title %></h1></p>

			<p>
			  <h2>Body:</h2>
			  <h4><%= @blog.body %></h4>
			</p>

			<p>
			  <h2>Date:</h2>
			  <h4><%= @blog.date %></h4>
			</p>

			<br />

			<%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-block btn-info" %>

			<br />

			<%= link_to 'Back', blogs_path, class: "btn btn-block btn-primary" %>
		</div>
	</div>
</div>
<div class="col-md-4"></div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/home/about.html.erb
<!DOCTYPE html>
<html >
<head>
	<%= render 'shared/nav' %>
  <meta charset="UTF-8">
  <title>Snake Game - CSS Renderer</title>
  <script src="https://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

  
      <link rel="stylesheet" href="/assets/about.scss">

  
</head>

<body>
  <div class="score">0</div>
<div class="stage"></div>
  
    <script  src="/assets/about.js"></script>

</body>
</html>

app/views/home/home.html.erb
<!DOCTYPE html>
<html >
<head>
	<%= render 'shared/nav' %>
  <meta charset="UTF-8">
  <title>Wave text effect (with SVG/blend mode)</title>
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  
      <link rel="stylesheet" href="/assets/home.scss">

  
</head>

<body>
  <link href='http://fonts.googleapis.com/css?family=Cabin+Condensed:700' rel='stylesheet' type='text/css'>

<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="450px" height="240px" xml:space="preserve">
  <defs>
    <pattern id="water" width=".25" height="1.1" patternContentUnits="objectBoundingBox">
      <path fill="#000" d="M0.25,1H0c0,0,0-0.659,0-0.916c0.083-0.303,0.158,0.334,0.25,0C0.25,0.327,0.25,1,0.25,1z"/>
    </pattern>
    
    <text id="text" transform="translate(2,116)" font-family="'Cabin Condensed'" font-size="161.047">HOME</text>
    
    <mask id="text-mask">
      <use x="0" y="0" xlink:href="#text" opacity="1" fill="#ffffff"/>
    </mask>
    
    <g id="eff">
      <use x="0" y="0" xlink:href="#text" fill="#a2a3a5"/>
  
  <rect class="water-fill" mask="url(#text-mask)" fill="url(#water)" x="-300" y="50" width="1200" height="120" opacity="0.3">
    <animate attributeType="xml" attributeName="x" from="-300" to="0" repeatCount="indefinite" dur="2s"/>
  </rect>
   <rect class="water-fill" mask="url(#text-mask)" fill="url(#water)" y="45" width="1600" height="120" opacity="0.3">
    <animate attributeType="xml" attributeName="x" from="-400" to="0" repeatCount="indefinite" dur="3s"/>
  </rect>
      
  <rect class="water-fill" mask="url(#text-mask)" fill="url(#water)" y="55" width="800" height="120" opacity="0.3">
    <animate attributeType="xml" attributeName="x" from="-200" to="0" repeatCount="indefinite" dur="1.4s"/>
  </rect>
      <rect class="water-fill" mask="url(#text-mask)" fill="url(#water)" y="55" width="2000" height="120" opacity="0.3">
    <animate attributeType="xml" attributeName="x" from="-500" to="0" repeatCount="indefinite" dur="2.8s"/>
  </rect>
    </g>
  </defs>
 
	  <use xlink:href="#eff" opacity="0.9" style="mix-blend-mode:color-burn"/>

</svg>
  
  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newappforclass</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_logout.html.erb
<div class="out-lg">
  <% if logged_in?(:user, :admin) %>
  	<%= link_to '', edit_user_registration_path, class: 'glyphicon glyphicon-cog set-index-icons' %>
    <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "btn btn-danger" %>
  <% else %>
    <%= link_to 'Register', new_user_registration_path %>
    <%= link_to 'Login', new_user_session_path %>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-6">
			<div class="nav-main">
				<ul class="custom-nav nav nav-pills">
				  <li role="presentation", class="<%= active?(home_path) %>">
				  	<%= link_to "Home", home_path %>
				  </li>
				  <li role="presentation", class="<%= active?(about_path) %>">
				  	<%= link_to "About", about_path %>
				  </li>
				  <li role="presentation", class="<%= active?(root_path) %>">
				  	<%= link_to "Blogs", root_path %>
				  </li>
				  <li role="presentation", class="<%= active?(new_charge_path) %>">
				  	<%= link_to "Donate", new_charge_path %>
				  </li>
				  <li role="presentation">
				  	<% if current_user.roles.include?(:admin) %>
							<%= link_to "Admin Dashboard", admin_root_path %>
						<% end %>
					</li>
				</ul>
			</div>
		</div>
		<div class="col-md-4"></div>
		<%= render 'shared/logout' %>
	</div>
</div>